### ISSUE TITLE
Add some documentation for organizers/lead coordinators

### ISSUE THREAD

**Issue by mxie** [railsbridge-boston/cookbook#9]
I think we do a pretty good job with outlining the responsibilities of and providing detailed how-to's for all roles, except the organizer/lead coordinator.

We should fix that.

Information should include the general timeline of everything, how to find information, who to contact for what, etc.

Any insight from @danchoi @bcarreno @janetriley @gabebw would be great.

**Comment by gabebw** [comment]
Can we get all this information by reading this: https://github.com/railsbridge-boston/cookbook/blob/master/task-descriptions.md ?

To be clear: I think we should make a separate document for this, but is it all kind of written down right now, but super disorganized?

**Comment by danchoi** [comment]
I just added text about the lead organizer responsibility to 

  https://github.com/railsbridge-boston/cookbook/blob/master/task-descriptions.md#lead-organizers

I don't know what the time commitment for lead organizer is like these
days, but in the beginning when we didn't have as many volunteers or as
much prior experience to draw from it was over 80 hours per workshop
(per lead organizer). I am hoping that it is less now.  I just put up 40
hours as a ballpark estimate. Melissa and Janet please adjust that
figure according to what you've experienced.

Dan

On Tue, Jan 27, 2015 at 11:41 AM, Melissa Xie <notifications@github.com> wrote:

> from: Melissa Xie <notifications@github.com>
> date: Tue, Jan 27 08:41 AM -08:00 2015
> to: railsbridge-boston/cookbook <cookbook@noreply.github.com>
> cc: Daniel Choi <dhchoi@gmail.com>
> reply-to: railsbridge-boston/cookbook <reply@reply.github.com>
> subject: [cookbook] Add some documentation for organizers/lead coordinators (#9)
> 
> I think we do a pretty good job with outlining the responsibilities of and providing detailed how-to's for all roles, except the organizer/lead coordinator.
> 
> We should fix that.
> 
> Information should include the general timeline of everything, how to find information, who to contact for what, etc.
> 
> Any insight from @danchoi @bcarreno @janetriley @gabebw would be great.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/railsbridge-boston/cookbook/issues/9

---
Sent from Vmail
http://danielchoi.com/software/vmail.html

**Comment by mxie** [comment]
Thanks Dan!

@gabebw - I think you have a good point there. That Task Descriptions page pretty much captures everything that needs to be taken care of, so perhaps reorganizing that information will fix this issue. What I had in mind was something like a "Quick Start Guide" for organizers -- something that outlined what their responsibilities are, what the commitment looks like. Dan's addition just now is a good start.

**Comment by gabebw** [comment]
Great, i agree
